/* tslint:disable */
/* eslint-disable */
/**
 * FantasyStore
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomTokenObtainPairRequest
 */
export interface CustomTokenObtainPairRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomTokenObtainPairRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof CustomTokenObtainPairRequest
     */
    'password': string;
}

