/* tslint:disable */
/* eslint-disable */
/**
 * FantasyStore
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageType } from './image-type';

/**
 * 
 * @export
 * @interface ImageSerializerRequest
 */
export interface ImageSerializerRequest {
    /**
     * 
     * @type {number}
     * @memberof ImageSerializerRequest
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ImageSerializerRequest
     */
    'image': string;
    /**
     * 
     * @type {ImageType}
     * @memberof ImageSerializerRequest
     */
    'type'?: ImageType;
}

