/* tslint:disable */
/* eslint-disable */
/**
 * FantasyStore
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `AC` - Activo * `IN` - Inicio * `PR` - En progreso * `DN` - Denegado * `UP` - Sin pago
 * @export
 * @enum {string}
 */

export const StatusEnum = {
    Ac: 'AC',
    In: 'IN',
    Pr: 'PR',
    Dn: 'DN',
    Up: 'UP'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];



