/* tslint:disable */
/* eslint-disable */
/**
 * FantasyStore
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `WK` - Trabajando * `NWK` - No trabajando * `AB` - Disponible * `BS` - Ocupado
 * @export
 * @enum {string}
 */

export const StatusDeliveryEnum = {
    Wk: 'WK',
    Nwk: 'NWK',
    Ab: 'AB',
    Bs: 'BS'
} as const;

export type StatusDeliveryEnum = typeof StatusDeliveryEnum[keyof typeof StatusDeliveryEnum];



