/* tslint:disable */
/* eslint-disable */
/**
 * FantasyStore
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'identification'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'phone'?: string | null;
}

